// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgtbsquhwpdislumieej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndGJzcXVod3BkaXNsdW1pZWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzA0MDQsImV4cCI6MjA2Nzc0NjQwNH0.iNY2zzzLw9Y869Fs-Ll2zVqTnEu8WzMbEa9XXcLWMUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});